-- Import App VM Identity into Postgres
SELECT * FROM pgaadauth_create_principal('${APP_IDENTITY_NAME}', false, false);

-- Grant privileges to application database
GRANT CONNECT ON DATABASE ${DB_NAME} TO "${APP_IDENTITY_NAME}";
GRANT USAGE ON SCHEMA public TO "${APP_IDENTITY_NAME}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${APP_IDENTITY_NAME}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_IDENTITY_NAME}";